<a href="https://colab.research.google.com/github/moshebou/ML-Bootcamp/blob/master/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline


# What is PyTorch?
# ================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

# Getting Started
---------------

# Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0240e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0680, 0.3784, 0.9910],
        [0.1801, 0.6394, 0.5362],
        [0.1788, 0.8684, 0.5042],
        [0.9770, 0.9014, 0.8020],
        [0.8630, 0.2094, 0.6852]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3771, -0.4550, -1.2535],
        [ 1.8489,  1.0576, -0.4640],
        [-0.5890,  0.6178, -0.3490],
        [ 0.6042, -0.2073, -1.1331],
        [-0.0419, -0.3390,  0.1275]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>torch.Size is in fact a tuple, so it supports all tuple operations.</p></div>



# Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.5586, -0.0139, -0.9071],
        [ 2.0178,  1.8980, -0.1624],
        [-0.1424,  1.6018,  0.3834],
        [ 0.7986, -0.0144, -0.2026],
        [ 0.3748,  0.3984,  1.0032]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[ 0.5586, -0.0139, -0.9071],
        [ 2.0178,  1.8980, -0.1624],
        [-0.1424,  1.6018,  0.3834],
        [ 0.7986, -0.0144, -0.2026],
        [ 0.3748,  0.3984,  1.0032]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5586, -0.0139, -0.9071],
        [ 2.0178,  1.8980, -0.1624],
        [-0.1424,  1.6018,  0.3834],
        [ 0.7986, -0.0144, -0.2026],
        [ 0.3748,  0.3984,  1.0032]])


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5586, -0.0139, -0.9071],
        [ 2.0178,  1.8980, -0.1624],
        [-0.1424,  1.6018,  0.3834],
        [ 0.7986, -0.0144, -0.2026],
        [ 0.3748,  0.3984,  1.0032]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])

tensor([-0.4550,  1.0576,  0.6178, -0.2073, -0.3390])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0011])
-0.0011051000328734517


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described [here](https://pytorch.org/docs/stable/torch.html).


# NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
---

In [0]:
a = torch.ones(5)
print(a)

In [0]:
b = a.numpy()
print(b)

See how the numpy array changed in value.



In [0]:
a.add_(1)
print(a)
print(b)

Converting NumPy Array to Torch Tensor
------------


See how changing the np array changed the Torch Tensor automatically


In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [3]:
import torch
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
  x = torch.randn(4, 4)
  device = torch.device("cuda")          # a CUDA device object
  y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
  x = x.to(device)                       # or just use strings ``.to("cuda")``
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[-0.0037,  0.9306,  1.9781,  0.9183],
        [ 0.6388,  1.7891,  0.2430,  0.1573],
        [ 1.3385,  0.9870,  1.8087,  0.6964],
        [ 1.8542,  0.8985,  1.8356,  3.2063]], device='cuda:0')
tensor([[-0.0037,  0.9306,  1.9781,  0.9183],
        [ 0.6388,  1.7891,  0.2430,  0.1573],
        [ 1.3385,  0.9870,  1.8087,  0.6964],
        [ 1.8542,  0.8985,  1.8356,  3.2063]], dtype=torch.float64)
